discovery.zen.minimum_master_nodes: 1

#network.host:
#- 127.0.0.1


network.bind_host: 0.0.0.0
network.publish_host: 192.168.1.100
#network.publish_host: 127.0.0.1


# Enable scripting as described here: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting.html
script.inline: true
script.stored: true
script.file:   true
